WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Components/ProductListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Components
{
    public class ProductListViewComponent : ViewComponent
    {
        private IProductRepository _productRepo;

        public ProductListViewComponent(IProductRepository productRepository)
        {
            _productRepo = productRepository;
        }

        public IViewComponentResult Invoke(int count)
        {
            var items = _productRepo.GetAll();
            if(count > 0)
            {
                return View(items.Take(count).ToList());
            }
            return View(items);
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WiredBrainCoffeeAdmin.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Help.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class HelpModel : PageModel
    {
        private ITicketService _ticketService;

        [BindProperty]
        public HelpTicket NewTicket { get; set; }

        public string ResponseMessage { get; set; }
        
        public IList<HelpTicket> HelpTickets { get; set; }

        public HelpModel(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }

        public async Task<IActionResult> OnGet()
        {
            HelpTickets = await _ticketService.GetAll();

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            ResponseMessage = await _ticketService.Create(NewTicket);

            HelpTickets = await _ticketService.GetAll();

            return Page();
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IHttpClientFactory _clientFactory;

        public List<SurveyItem> SurveyResults { get; set; }

        public IDictionary<string, string> OrderStats { get; set; }

        public IndexModel(ILogger<IndexModel> logger, IHttpClientFactory factory)
        {
            _logger = logger;
            _clientFactory = factory;
        }

        public async void OnGet()
        {
            var client = _clientFactory.CreateClient();

            var response = await client.GetAsync("https://wiredbraincoffeeadmin.azurewebsites.net/api/orderStats");
            var responseData = await response.Content.ReadAsStringAsync();
            OrderStats = JsonSerializer.Deserialize<IDictionary<string, string>>(responseData);

            var rawJson = System.IO.File.ReadAllText("wwwroot/sampledata/survey.json");
            SurveyResults = JsonSerializer.Deserialize<List<SurveyItem>>(rawJson);
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WiredBrainCoffeeAdmin.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Products/AddProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class AddProductModel : PageModel
    {
        private IProductRepository _productRepo;
        private IWebHostEnvironment _webEnv;

        public AddProductModel(IProductRepository productRepository, IWebHostEnvironment environment)
        {
            _productRepo = productRepository;
            _webEnv = environment;
        }

        [BindProperty]
        public Product NewProduct { get; set; } = new Product();

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) { return Page(); }

            if (NewProduct.Upload is not null)
            {
                NewProduct.ImageFileName = NewProduct.Upload.FileName;

                var file = Path.Combine(_webEnv.ContentRootPath, "wwwroot/images/menu", NewProduct.Upload.FileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await NewProduct.Upload.CopyToAsync(fileStream);
                }
            }

            NewProduct.Created = DateTime.Now;
            _productRepo.Add(NewProduct);

            return RedirectToPage("ViewAllProducts");
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Products/EditProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data.Models;
using WiredBrainCoffeeAdmin.Data;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class EditProductModel : PageModel
    {
        private IProductRepository _productRepo;
        private IWebHostEnvironment _webEnv;

        public EditProductModel(IProductRepository productRepository, IWebHostEnvironment environment)
        {
            _productRepo = productRepository;
            _webEnv = environment;
        }

        [FromRoute]
        public int Id { get; set; }

        [BindProperty]
        public Product EditProduct { get; set; }

        public void OnGet()
        {
            EditProduct = this._productRepo.GetById(Id);
        }

        public async Task<IActionResult> OnPostEdit()
        {
            if (!ModelState.IsValid)
            { return Page(); }

            if (EditProduct.Upload is not null)
            {
                EditProduct.ImageFileName = EditProduct.Upload.FileName;

                var file = Path.Combine(_webEnv.ContentRootPath, "wwwroot/images/menu", EditProduct.Upload.FileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await EditProduct.Upload.CopyToAsync(fileStream);
                }
            }

            EditProduct.Created = DateTime.Now;
            EditProduct.Id = Id;
            _productRepo.Update(EditProduct);

            return RedirectToPage("ViewAllProducts");
        }

        public IActionResult OnPostDelete()
        {
            _productRepo.Delete(Id);
            return RedirectToPage("ViewAllProducts");
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Products/ViewAllProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffeeAdmin.Data;
using WiredBrainCoffeeAdmin.Data.Models;

namespace WiredBrainCoffeeAdmin.Pages.Products
{
    public class ViewAllProductsModel : PageModel
    {
        private IProductRepository _productRepo;

        public IList<Product> Products { get; set; }

        public ViewAllProductsModel(IProductRepository productRepository)
        {
            _productRepo = productRepository;
        }

        public void OnGet()
        {
            Products = _productRepo.GetAll();
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Shared/Info.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WiredBrainCoffeeAdmin.Pages.Shared
{
    public class InfoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Help.cshtml
@page "/help"
@model WiredBrainCoffeeAdmin.Pages.HelpModel
@{
}

<h1 class="h2">Request Help</h1>
<hr />

@if (!string.IsNullOrWhiteSpace(Model.ResponseMessage))
{
    <p class="alert alert-info">@Model.ResponseMessage</p>
}

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                Request Help
            </div>
            <div class="card-body">
                <h5 class="card-title">Contact out IT Team</h5>
                <p class="card-text">Having an issue with the site? Let us know!</p>
                <form method="post" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label asp-for="NewTicket.Title" class="form-label">Title</label>
                        <input asp-for="NewTicket.Title" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label asp-for="NewTicket.Description" class="form-label">Description</label>
                        <textarea asp-for="NewTicket.Description" class="form-control"></textarea>
                    </div>
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <h2>Current Issues</h2>
        <hr />
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.HelpTickets)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Title</td>
                        <td>@item.Description</td>
                        <td>@item.Status</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/HelpWidget.cshtml
<div class="card-header">
    Request Help
</div>
<div class="card-body">
    <h5 class="card-title">Contact out IT Team</h5>
    <p class="card-text">Having an issue with the site?  Let us know!</p>
    <a asp-page="help" class="btn btn-success">Request Help</a>
</div>

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container-fluid dashboard">
    <h1 class="h2">Welcome to Wired Brain Coffee!</h1>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <h2>Latest Products</h2>
            <vc:product-list count="4" />
            <h2>Latest Survey Results</h2>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Question</th>
                        <th>Answer</th>
                    </tr>
                </thead>
                <tbody>
                @foreach(var item in Model.SurveyResults)
                {
                    <tr>
                        <td>@item.Question</td>
                        <td>@item.Answer</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <div class="card-header">
                The Basics
            </div>
            <div class="card-body">
                <p>Hello, today is @DateTime.Today.Date.ToString("MM/dd/yyyy").</p>
                @{
                    var temperature = 55;
                }
                <p>The current temperature is @temperature degrees.</p>
                @if(temperature < 60)
                {
                    <p>We recommend a coat unti it warms up @(60 - temperature) degrees.
                    </p>
                }
            </div>
            <partial name="HelpWidget" />
            <h2>Weekly Order Stats</h2>
            <table class="table table-bordered table-striped">
                @foreach(var item in Model.OrderStats)
                {
                    <tr>
                        <td>@item.Key</td>
                        <td>@item.Value</td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/ProductForm.cshtml
@using WiredBrainCoffeeAdmin.Data.Models
@model Product

<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="@Model.Name" class="form-label">Name</label>
        <input asp-for="@Model.Name" class="form-control" />
        <span asp-validation-for="@Model.Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.ShortDescription" class="form-label">Short Description</label>
        <input asp-for="@Model.ShortDescription" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Description" class="form-label">Description</label>
        <textarea asp-for="@Model.Description" class="form-control"></textarea>
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Price" class="form-label">Price</label>
        <input asp-for="@Model.Price" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="@Model.Category" class="form-label">Category</label>
        <select asp-for="@Model.Category" class="form-control">
            <option value="Beverage">Beverage</option>
            <option value="Food">Food</option>
        </select>
    </div>
    @if (ViewContext.RouteData.Values["id"] is not null)
    {
        <div class="mb-3">
            <label asp-for="@Model.ImageFileName" class="form-label">Current Image</label>
            <input type="hidden" asp-for="@Model.ImageFileName" class="form-control" />
            <img src="~/images/menu/@Model.ImageFileName" />
        </div>
    }
    <div class="mb-3">
        <label asp-for="@Model.Upload" class="form-label">Image</label>
        <input asp-for="@Model.Upload" class="form-control" />
    </div>
    @if (ViewContext.RouteData.Values["id"] is not null)
    {
        <button asp-page-handler="edit" class="btn btn-success">Submit</button>
        <button asp-page-handler="delete" class="btn btn-danger float-end">Delete</button>
    }
    else
    {
        <button class="btn btn-success">Add</button>
    }
</form>

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Products/AddProduct.cshtml
@page "/products/add"
@model WiredBrainCoffeeAdmin.Pages.Products.AddProductModel
@{
}

<h1>Add New Product</h1>
<hr />

<div class="row">
    <div class="col-md-6">
        <partial name="ProductForm" model="@Model.NewProduct" />
    </div>
    <div class="col-md-6">
        <partial name="HelpWidget" />
    </div>
</div>
@section RightFooter {
    <img src="~/images/menu/cappucino.png" />
}

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Products/EditProduct.cshtml
@page "/products/edit/{id:int}"
@model WiredBrainCoffeeAdmin.Pages.Products.EditProductModel
@{
}

<h1>Edit Product @($"\"{Model.EditProduct.Name}\"") <!-- @RouteData.Values["id"] --></h1>
<hr />

<div class="row">
    <div class="col-md-6">
        <partial name="ProductForm" model="@Model.EditProduct" />
    </div>
    <div class="col-md-6">
        <partial name="HelpWidget" />
    </div>
</div>

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Products/ViewAllProducts.cshtml
@page "/products/all"
@model WiredBrainCoffeeAdmin.Pages.Products.ViewAllProductsModel
@{
}

<h1>All Products</h1>
<hr />

<vc:product-list count="0" />

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Shared/Components/ProductList/Default.cshtml
@using WiredBrainCoffeeAdmin.Data.Models
@model IList<Product>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>ShortDescription</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td><img src="~/images/menu/@item.ImageFileName" /></td>
                <td>@item.Name</td>
                <td>@item.Category</td>
                <td>@item.Price</td>
                <td>@item.ShortDescription</td>
                <td><a asp-page="EditProduct" asp-route-id="@item.Id" class="btn btn-success">Edit</a></td>
            </tr>
        }
    </tbody>
</table>

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Shared/Info.cshtml
<div class="card">
    <div class="card-header">
        The Basics
    </div>
    <div class="card-body">
        <p>Hello, today is @DateTime.Today.Date.ToString("MM/dd/yyyy").</p>
        @{
            var temperature = 58;
        }
        <p>The current temperature is @temperature degrees.</p>
        @if (temperature < 60)
        {
            <p>We recommend a coat until it warms up another @(65 - temperature) degrees!</p>
        }
    </div>
</div>

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WiredBrainCoffeeAdmin</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment names="Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WiredBrainCoffeeAdmin.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" asp-page="/Index" aria-current="page">Dashboard</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Products</a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledBy="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-page="/products/viewallproducts">View All</a></li>
                                    <li><a class="dropdown-item" asp-page="/products/addproduct">Add New</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled">Orders (Coming soon)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-page="/help">Help</a>
                            </li>
                        </ul>
                    </div>
                    <a class="navbar-brand float-right">Wired Brain Coffee</a>
                </div>
            </nav>
        </header>
        <main>
            @RenderBody()
        </main>
        <footer>
            <div class="row">
                <div class="col-md-4">
                    <p>&copy; 2022 - WiredBrainCoffeeAdmin</p>
                    <img id="logo" src="~/images/wired-brain-coffee-logo.png" />
                </div>
                <div class="col-md-4">
                    <p>1234 Wired Brain Way</p>
                    <p>Awesome City, CA 55555</p>
                    <p>Phone: 555-123-4567</p>
                    <p>Fax: 555-123-4567</p>
                </div>
                <div class="col-md-4">
                    <div class="footer-pic">
                        @if (IsSectionDefined("RightFooter"))
                        {
                            @RenderSection("RightFooter")
                        }
                        else
                        {
                            <img src="~/images/menu/salad-house.png" />
                        }
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script scr="~/js/site.js" asp-append-version="true"></script>

    <partial name="_ValidationScriptsPartial" />

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WiredBrainCoffeeAdmin/WiredBrainCoffeeAdmin/Pages/Shared/_LayoutFluid.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WiredBrainCoffeeAdmin</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment names="Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WiredBrainCoffeeAdmin.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" asp-page="/Index" aria-current="page">Dashboard</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Products</a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledBy="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-page="/products/viewallproducts">View All</a></li>
                                    <li><a class="dropdown-item" asp-page="/products/addproduct">Add New</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled">Orders (Coming soon)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-page="/help">Help</a>
                            </li>
                        </ul>
                    </div>
                    <a class="navbar-brand float-right">Wired Brain Coffee</a>
                </div>
            </nav>
        </header>
        <main>
            @RenderBody()
        </main>
        <footer>
            <div class="row">
                <div class="col-md-4">
                    <p>&copy; 2022 - WiredBrainCoffeeAdmin</p>
                    <img id="logo" src="~/images/wired-brain-coffee-logo.png" />
                </div>
                <div class="col-md-4">
                    <p>1234 Wired Brain Way</p>
                    <p>Awesome City, CA 55555</p>
                    <p>Phone: 555-123-4567</p>
                    <p>Fax: 555-123-4567</p>
                </div>
                <div class="col-md-4">
                    <div class="footer-pic">
                        @{
                            var urlPath = Context.Request.Path;
                        }

                        @switch (urlPath.Value.ToLower())
                        {
                            case "/":
                                <img src="~/images/menu/cake.png" />
                                break;
                            case "/products/addproduct":
                                <img src="~/images/menu/waffles.png" />
                                break;
                            case "/products/viewallproducts":
                                <img src="~/images/menu/salad-house.png" />
                                break;
                            case "/help":
                                <img src="~/images/menu/cappucino.png" />
                                break;
                        }
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script scr="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>